apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: set-vm-max-map-count
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: set-vm-max-map-count
  template:
    metadata:
      labels:
        app: set-vm-max-map-count
    spec:
      hostPID: true
      containers:
        - name: sysctl
          image: busybox
          command:
            - sh
            - '-c'
            - |
              sysctl -w vm.max_map_count=262144
          securityContext:
            privileged: true
